CREATE TABLE IF NOT EXISTS `tech_english_corpus` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '技术英语语料主键',
    `corpus_uuid` CHAR(36) NOT NULL COMMENT '语料稳定归属标识，用于后续对象存储和索引',
    `corpus_type` VARCHAR(20) NOT NULL COMMENT '语料类型：VOCABULARY词汇、SENTENCE语句、IMAGE图片、ARTICLE文章',
    `title` VARCHAR(160) NOT NULL COMMENT '语料标题或检索名称',
    `english_text` TEXT NULL COMMENT '英文词汇、句子、图片说明或文章摘录',
    `phonetic` VARCHAR(120) NULL COMMENT '词汇音标或发音提示',
    `explanation` VARCHAR(1000) NULL COMMENT '人工说明、使用场景或语法备注',
    `article_markdown` LONGTEXT NULL COMMENT '英语文章Markdown正文',
    `image_url` VARCHAR(2048) NULL COMMENT '图片公网或受控访问地址',
    `image_object_key` VARCHAR(500) NULL COMMENT '图片私有对象键，后续接入上传后写入',
    `image_alt` VARCHAR(300) NULL COMMENT '图片替代文本和识别说明',
    `source_name` VARCHAR(120) NULL COMMENT '语料来源名称',
    `source_url` VARCHAR(2048) NULL COMMENT '语料来源链接',
    `scenario` VARCHAR(80) NULL COMMENT '技术场景，如frontend、backend、database、ai',
    `difficulty` VARCHAR(16) NOT NULL DEFAULT 'INTERMEDIATE' COMMENT '难度：BEGINNER、INTERMEDIATE、ADVANCED',
    `tags` VARCHAR(500) NULL COMMENT '英文逗号分隔的轻量标签',
    `translation_text` TEXT NULL COMMENT '人工翻译或未来翻译API结果',
    `translation_status` VARCHAR(16) NOT NULL DEFAULT 'NONE' COMMENT '翻译状态：NONE无、PENDING待翻译、READY已完成、FAILED失败',
    `ai_review_status` VARCHAR(16) NOT NULL DEFAULT 'NOT_REQUIRED' COMMENT 'AI处理状态：NOT_REQUIRED、PENDING、REVIEWED、FAILED',
    `ai_review_notes` VARCHAR(1000) NULL COMMENT '未来AI抽取、纠错或审核摘要',
    `index_status` VARCHAR(16) NOT NULL DEFAULT 'NOT_INDEXED' COMMENT '搜索索引状态：NOT_INDEXED、PENDING、SUCCEEDED、FAILED',
    `content_version` BIGINT NOT NULL DEFAULT 1 COMMENT '内容版本号，每次保存递增',
    `status` VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '发布状态：DRAFT草稿、PUBLISHED已发布',
    `published_at` DATETIME NULL COMMENT '最近发布时间',
    `createtime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updatetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `createby` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人，0表示管理后台',
    `updateby` BIGINT NOT NULL DEFAULT 0 COMMENT '更新人，0表示管理后台',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常、1已删除',
    `reserved1` VARCHAR(255) NULL COMMENT '冗余字段1',
    `reserved2` VARCHAR(255) NULL COMMENT '冗余字段2',
    `reserved3` VARCHAR(255) NULL COMMENT '冗余字段3',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tech_english_corpus_uuid` (`corpus_uuid`),
    KEY `idx_tech_english_corpus_type_status` (`corpus_type`, `status`, `deleted`, `updatetime`, `id`),
    KEY `idx_tech_english_corpus_title` (`title`),
    KEY `idx_tech_english_corpus_scenario` (`scenario`, `deleted`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='技术英语语料库';
