CREATE TABLE IF NOT EXISTS `tech_english_ai_recognition_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '识图任务记录主键',
    `session_uuid` CHAR(36) NOT NULL COMMENT '页面一次上传会话标识',
    `batch_uuid` CHAR(36) NOT NULL COMMENT '单个AI识别批次标识',
    `status` VARCHAR(20) NOT NULL COMMENT '任务状态：PROCESSING、RECOGNIZED、FAILED、IMPORTED',
    `source_name` VARCHAR(120) NOT NULL COMMENT '识图资料来源',
    `scenario` VARCHAR(80) NULL COMMENT '扩展例句场景',
    `chunk_index` INT NOT NULL COMMENT '当前并发子任务序号，从1开始',
    `chunk_count` INT NOT NULL COMMENT '本次上传的子任务总数',
    `image_count` INT NOT NULL DEFAULT 0 COMMENT '当前子任务图片数',
    `item_count` INT NOT NULL DEFAULT 0 COMMENT '识别到的语料数',
    `example_count` INT NOT NULL DEFAULT 0 COMMENT '每条语料扩展例句数',
    `result_json` JSON NULL COMMENT '已清洗的识图预览结果JSON',
    `error_code` VARCHAR(80) NULL COMMENT '失败业务码',
    `error_message` VARCHAR(500) NULL COMMENT '可安全展示的失败说明',
    `completed_at` DATETIME NULL COMMENT '识别完成或失败时间',
    `imported_at` DATETIME NULL COMMENT '确认入库完成时间',
    `createtime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updatetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `createby` BIGINT NOT NULL DEFAULT 0 COMMENT '创建用户',
    `updateby` BIGINT NOT NULL DEFAULT 0 COMMENT '更新用户',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常、1已删除',
    `reserved1` VARCHAR(255) NULL COMMENT '冗余字段1',
    `reserved2` VARCHAR(255) NULL COMMENT '冗余字段2',
    `reserved3` VARCHAR(255) NULL COMMENT '冗余字段3',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tech_english_ai_recognition_batch` (`batch_uuid`),
    KEY `idx_tech_english_ai_recognition_session` (`createby`, `session_uuid`, `deleted`, `chunk_index`),
    KEY `idx_tech_english_ai_recognition_history` (`createby`, `deleted`, `createtime`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='技术英语AI识图任务永久记录';
