CREATE TABLE IF NOT EXISTS `sys_user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户主键',
    `username` VARCHAR(32) NOT NULL COMMENT '用户名',
    `phone` VARCHAR(20) NULL COMMENT '手机号，微信用户可在绑定前为空',
    `email` VARCHAR(128) NULL COMMENT '邮箱，微信用户可在绑定前为空',
    `password_hash` VARCHAR(100) NULL COMMENT 'BCrypt密码摘要，非密码用户可为空',
    `member_level` VARCHAR(20) NOT NULL DEFAULT 'GUEST' COMMENT '会员等级：SUPER超级会员、NORMAL普通会员、GUEST游客、BANNED已封禁',
    `member_expire_time` DATETIME NULL COMMENT '会员到期时间，为空表示未设置',
    `avatar_url` VARCHAR(500) NOT NULL DEFAULT '/default-avatar.svg' COMMENT '头像地址，当前仅允许默认头像',
    `auth_provider` VARCHAR(20) NOT NULL DEFAULT 'PASSWORD' COMMENT '注册来源：PASSWORD密码、WECHAT微信',
    `wechat_openid` VARCHAR(128) NULL COMMENT '微信OpenID，预留',
    `wechat_unionid` VARCHAR(128) NULL COMMENT '微信UnionID，预留',
    `last_login_time` DATETIME NULL COMMENT '最近登录时间',
    `createtime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updatetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `createby` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人，0表示系统',
    `updateby` BIGINT NOT NULL DEFAULT 0 COMMENT '更新人，0表示系统',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常、1已删除',
    `reserved1` VARCHAR(255) NULL COMMENT '冗余字段1',
    `reserved2` VARCHAR(255) NULL COMMENT '冗余字段2',
    `reserved3` VARCHAR(255) NULL COMMENT '冗余字段3',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_sys_user_username` (`username`),
    UNIQUE KEY `uk_sys_user_phone` (`phone`),
    UNIQUE KEY `uk_sys_user_email` (`email`),
    UNIQUE KEY `uk_sys_user_wechat_openid` (`wechat_openid`),
    UNIQUE KEY `uk_sys_user_wechat_unionid` (`wechat_unionid`),
    KEY `idx_sys_user_member_level` (`member_level`),
    KEY `idx_sys_user_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统用户表';
